### ISSUE TITLE
fPort needed for decoder

### ISSUE THREAD

**Issue by apachler** [aws-samples/aws-iot-core-lorawan#4]
# Issue
I am trying to implement a new decoder for a device that sends different messages on different ports.
Because the actual implementation of lambda_handler in app.py does not pass the fPort to the decoder, it is impossible to differentiate between these messages.

# Device
NAS Pulse Reader UM3080 [*specification*](https://www.nasys.no/wp-content/uploads/PULSE_READER_UM3080.pdf)

# Request
What would be the best approach to make the fPort available for the decoder?
- Passing the entire received event instead of just the PayloadData
- Passing the entire WirelessMetadata as optional parameter additionally to the PayloadData
- Passing the fPort as optional parameter additionally to the PayloadData

Any other ideas?

Just wanted to discuss how it should be implemented. I am going to do the whole refactoring for all decoders once the desired approach is defined.

Thanks!

**Comment by asvand** [comment]
Hi Andreas,

thanks for your feedback!

I suggest adjust app.py so that is passes he fPort as a parameter additionally to the PayloadData in the dict_from_payload function of the decoder. By doing so, we would make dict_from_payload logic agnostic of the invocation context or AWS IoT Core for LoRaWAN, so it could be reused by customers in other contexts.

Does it make sense for you? If you agree, I would make an according adjustment in app.py

**Comment by apachler** [comment]
Hi Andrei,

yes, that sounds good to me ;)

If you are done with your adjustments I am going to complete the NAS UM3080 payload decoder and create a pull request for it ...

Thanks!

**Comment by asvand** [comment]
Hi Andre, take a look at the implementation in branch feature/transform_binary_payload/fport:

https://github.com/aws-samples/aws-iot-core-lorawan/blob/feature/transform_binary_payload/fport/transform_binary_payload/src-payload-decoders/python/sample_device.py

app.py is also updated accordingly.

If that works for you, I will merge it into master.

**Comment by apachler** [comment]
Sure, that will work quite well 👍

**Comment by asvand** [comment]
Done!
