### ISSUE TITLE
eu-west-1 timestream cloudformation template not working

### ISSUE THREAD

**Issue by AdrianTayag** [aws-samples/aws-iot-core-lorawan#9]
Launching the timestream sample cloudformation stack for eu-west-1 results to errors and roll back. Status reason on the error suggests to launch via us-east-1 server.

On the other hand, launching via us-east-1 link works flawlessly.

**Comment by asvand** [comment]
Dear Adrian, first of all thanks for running a workshop and taking time to provide a feedback! I will be happy to help you to resolve the issue. I have tried reproducing the error you mentioned and have not been able to do so, so I want to ask you for some additional input:
1) Could you please see if you run the following CloudFormation template in eu-west-1:
https://aws-iot-workshop-iotcorelorawan-eu-west-1.s3.amazonaws.com/iotcorelorawan.workshop.aws/1.0.0/cfresources/cf-template-dontedit-eu-west-1.yaml

I am asking because there is also a template https://aws-iot-workshop-iotcorelorawan-us-east-1.s3.amazonaws.com/iotcorelorawan.workshop.aws/1.0.0/cfresources/cf-template-dontedit-us-east-1.yaml availble, which will only work in us-east-1

2) If you run the https://aws-iot-workshop-iotcorelorawan-eu-west-1.s3.amazonaws.com/iotcorelorawan.workshop.aws/1.0.0/cfresources/cf-template-dontedit-eu-west-1.yaml template, could you please paste the error description from CloudFormation here?

Thanks for your support and best regards,
Andrei

**Comment by AdrianTayag** [comment]
Hi Andrei, 

The link you provided has successfully created the CloudFormation template. 

I suggest that the link provided on the README.md on the Timestream folder be changed since I think it is where the issue is coming from. The yaml templates being used are the same unlike the one you gave me. See below.

us-east-1 link:
https://console.aws.amazon.com/cloudformation/home?region=us-east-1#/stacks/create/review?stackName=lorawan2timestream&templateURL=https://githubsample-aws-iot-core-lorawan-us-east-1.s3.amazonaws.com/integration/timestream/template/cf-template-dontedit.yaml

eu-west-1 link: 
https://console.aws.amazon.com/cloudformation/home?region=eu-west-1#/stacks/create/review?stackName=lorawan2timestream&templateURL=https://githubsample-aws-iot-core-lorawan-us-east-1.s3.amazonaws.com/integration/timestream/template/cf-template-dontedit.yaml

Best Regards,
Adrian
